language: ruby
 rvm:
   - 2.2
 before_script:
   - gem install awesome_bot
 script:
   - awesome_bot README.md --allow-dupe --white-list=https://www.amazon.com,https://youtu.be,https://testdriven.io,https://www.youtube.com/,https://www.amazon.com
